# Generated by Django 2.0 on 2018-07-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Name',
            new_name='name',
        ),
    ]
